apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc }}
  rabbitmq-username: {{ .Values.rabbitmq.username | b64enc }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc }}

