apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-management
spec:
  type: {{ .Values.service.management.type }}
  ports:
    - port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.port }}
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-internal
spec:
  type: {{ .Values.service.internal.type }}
  ports:
    - port: {{ .Values.service.internal.port }}
      targetPort: {{ .Values.service.internal.port }}
  selector:
    app: rabbitmq

